CLASS_TYPE_REGEX = "\'([\w\W]+)\'"
META_METHOD = "__[\w]+__"

BLOCK_SEQ_SEPARATOR = "- "
STRING_SEQ_SEPARATOR = ", "
NAME_VALUE_MATCHER = ": "
NAME_OBJECT_MATCHER = ":\n"
COMMENT_SYMBOL = "#"
TAB_LITERAL = "\t"

COMPLEX_OBJECT_NAME = "python/object"
TYPE_FIELD_NAME = "type"

YAML_TRUE = "True"
YAML_FALSE = "False"
YAML_NONE = "None"
